In [66]:
# !nvidia-smi

In [67]:
import os
HOME = os.getcwd()
print(HOME)

C:\Users\asus\Downloads\CarDamage\code\model\Dataset\Dataset\data\images\val


In [68]:
# !pip install ultralytics==8.0.20

In [69]:
# Pip install method (recommended)



from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

Ultralytics YOLOv8.2.28  Python-3.12.0 torch-2.5.0+cpu CPU (AMD Ryzen 7 5800H with Radeon Graphics)
Setup complete  (16 CPUs, 15.4 GB RAM, 511.6/642.9 GB disk)


In [70]:
from ultralytics import YOLO
from IPython.display import display, Image

In [71]:
import torch

## CLI Basics 

If you want to train, validate or run inference on models and don't need to make any modifications to the code, using YOLO command line interface is the easiest way to get started. Read more about CLI in [Ultralytics YOLO Docs](https://v8docs.ultralytics.com/cli/).

```
yolo task=detect    mode=train    model=yolov8n.yaml      args...
          classify       predict        yolov8n-cls.yaml  args...
          segment        val            yolov8n-seg.yaml  args...
                         export         yolov8n.pt        format=onnx  args...
```

## Inference with Pre-trained COCO Model

### 💻 CLI

`yolo mode=predict` runs YOLOv8 inference on a variety of sources, downloading models automatically from the latest YOLOv8 release, and saving results to `runs/predict`.

In [72]:
%cd {HOME}
!yolo task=detect mode=predict model=yolov8n.pt conf=0.25 source='https://media.roboflow.com/notebooks/examples/dog.jpeg'

C:\Users\asus\Downloads\CarDamage\code\model\Dataset\Dataset\data\images\val


c:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\IPython\core\magics\osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


Ultralytics YOLOv8.2.28 🚀 Python-3.12.0 torch-2.5.0+cpu CPU (AMD Ryzen 7 5800H with Radeon Graphics)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

Found https://media.roboflow.com/notebooks/examples/dog.jpeg locally at dog.jpeg
image 1/1 C:\Users\asus\Downloads\CarDamage\code\model\Dataset\Dataset\data\images\val\dog.jpeg: 640x384 1 person, 1 car, 1 dog, 281.9ms
Speed: 11.6ms preprocess, 281.9ms inference, 1.6ms postprocess per image at shape (1, 3, 640, 384)
Results saved to runs\detect\predict2
💡 Learn more at https://docs.ultralytics.com/modes/predict


C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\nn\tasks.py:732: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(file, ma

In [73]:
# %cd {HOME}
# Image(filename='runs/detect/predict/dog.jpeg', height=600)

### 🐍 Python SDK

The simplest way of simply using YOLOv8 directly in a Python environment.

In [74]:
model = YOLO(f'{HOME}/yolov8n.pt')
results = model.predict(source='https://media.roboflow.com/notebooks/examples/dog.jpeg', conf=0.25)

c:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\nn\tasks.py:732: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(file, ma


Found https://media.roboflow.com/notebooks/examples/dog.jpeg locally at dog.jpeg
image 1/1 C:\Users\asus\Downloads\CarDamage\code\model\Dataset\Dataset\data\images\val\dog.jpeg: 640x384 1 person, 1 car, 1 dog, 210.3ms
Speed: 3.5ms preprocess, 210.3ms inference, 1.7ms postprocess per image at shape (1, 3, 640, 384)


In [75]:
results[0].boxes.xyxy

tensor([[   0.0000,  314.4714,  625.0755, 1278.1946],
        [  55.1731,  250.0220,  648.1080, 1266.2720],
        [ 633.2290,  719.5391,  701.0540,  786.0336]])

In [76]:
results[0].boxes.conf

tensor([0.7271, 0.2907, 0.2846])

In [77]:
results[0].boxes.cls

tensor([ 0., 16.,  2.])

## Custom Training

In [78]:
# from google.colab import drive
# drive.mount('/content/drive')

In [79]:
%cd C:\Users\asus\Downloads\CarDamage\code\model\Dataset\Dataset\data\images\val

%cd C:\Users\asus\Downloads\CarDamage\code\model\Dataset\Dataset\data\images\val

C:\Users\asus\Downloads\CarDamage\code\model\Dataset\Dataset\data\images\val
C:\Users\asus\Downloads\CarDamage\code\model\Dataset\Dataset\data\images\val


In [80]:
%cd C:\Users\asus\Downloads\CarDamage\code\model\Dataset\Dataset\data\images\train
!yolo task=detect mode=train model=yolov8s.pt data = data.yaml epochs=100 imgsz=224 plots=True

C:\Users\asus\Downloads\CarDamage\code\model\Dataset\Dataset\data\images\train
New https://pypi.org/project/ultralytics/8.3.105 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.2.28 🚀 Python-3.12.0 torch-2.5.0+cpu CPU (AMD Ryzen 7 5800H with Radeon Graphics)
engine\trainer: task=detect, mode=train, model=yolov8s.pt, data=data.yaml, epochs=100, time=None, patience=100, batch=16, imgsz=224, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train2, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnost

C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\nn\tasks.py:732: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(file, ma

In [81]:
# !ls runs/detect/train/

In [82]:
Image(filename='runs/detect/train7/confusion_matrix.png', width=600)

FileNotFoundError: [Errno 2] No such file or directory: 'runs/detect/train7/confusion_matrix.png'

In [ ]:
Image(filename='C:\Users\IT Support\Downloads\yolov8\YOLO-v8-Object-Detection-main\yolo-V8\runs\detect\train7\results.png', width=600)

In [ ]:
Image(filename='runs/detect/train6/val_batch0_pred.jpg', width=600)

## Validate Custom Model

In [ ]:
!yolo task=detect mode=val model=runs/detect/train2/weights/best.pt data=data.yaml

## Inference with Custom Model

In [ ]:
!yolo task=detect mode=predict model=runs/detect/train2/weights/best.pt conf=0.25 source=data/test/images

**NOTE:** Let's take a look at few results.

In [ ]:
import glob
from IPython.display import Image, display

for image_path in glob.glob('runs/detect/predict/*.jpg')[:3]:
      display(Image(filename=image_path, width=600))
      print("\n")